### PR TITLE
Update Evil Portal with set_ap and select_html

### PR DESCRIPTION
**Pull request by agentzex**
This updates Mayhem Evil Portal with these 2 features that enables the user to set the AP name of the Evil Portal from the flipper, and also to select HTML for the Captive Portal main page (index.html) from  a directory in the Flipper SDcard. As seen here https://github.com/leedave/flipper-zero-evil-portal/tree/leedave/ap_rename

### CODE REVIEW

**Comment by eried** [comment]
Hi! Thanks for the PR, were you able to make it work at the end? (Tested, etc)

**Comment by agentzex** [comment]
It was tested couple of times maybe, before I tried to push some additional changes, then my Mayhem stopped working :( .
For sure require some additional testing, especially for the select HTML part.

**Comment by eried** [comment]
Marauder includes evil portal, so eventually I will merge that version :)

**Comment by agentzex** [comment]
You mean the official Marauder repo https://github.com/justcallmekoko/ESP32Marauder ? 
Where does it have the Flipper GUI (FAP) code ? isn't that only the esp32 side ?

**Comment by eried** [comment]
It is both, there is a new menu. Check: https://flipper.ried.cl/webinstaller/

**Comment by agentzex** [comment]
I saw a lot was changed with that new orgnaization.
Well for the meantime they still miss those new , IMHO , very required features for practical attacks like these , like setting AP name\domain name for the captive portal, setting the html via the flipper app itself (currently it just takes the index.html file from a known path on the SD, but let's say you want to switch html pages on the fly, you'll need to connect the SD each time, replace those files on your PC and then restart the attack, which isn't very optimal).
Also the way the Captive Portal, on the ESP32 side, is implemented isn't according to the RFC (this is what I started working and wanted to continue working on when my Mayhem board will be available again) .
Maybe I'll try to push some changes in the main Marauder  repo and then they will be consumed here as well eventually, I'll see :)

**Comment by eried** [comment]
Yeah, I can accept any PR that is tested 😉

As for the features, I dont want to drift too much from any of these projects, since I am the only maintaining the code. Every update will be a lot of work. I guess those features will be included on next marauder.

**Comment by agentzex** [comment]
sure , I understand .

**Pull request closed without merging**
