### PR TITLE
Update marauder companion to 0.7.1

### PR DESCRIPTION
**Pull request by runcom**
This is based on https://github.com/eried/flipperzero-mayhem/pull/48 - let me know if you want them together but I think it's cleaner like this

### CODE REVIEW

**Comment by eried** [comment]
Awesome! thanks

**Comment by eried** [comment]
(I think is fine as is now, I will test on the weekend and let you know)

**Comment by runcom** [comment]
> (I think is fine as is now, I will test on the weekend and let you know)

awesome, I've rebased and tested on my fz and it seems to work just fine, I'll do more testing over the weekend too

**Comment by runcom** [comment]
ready and I haven't disabled wardrive here - so I'm gonna close #47 in favor of this and we keep the discussion on that enablement here

> > Yeah, I am not sure, what do you suggest for this kind of "optional" features?

> I think it could just work like it does with justcallmekoko's marauder - you build the functionality in and it's left to the user to install a GPS 🤷 if they select wardrive and there's no gps, since there are HAS_GPS ifdefs, worst case it doesn't log gps data right?

**Comment by runcom** [comment]
new push fixes baudrate for FZ, ufbt compilation and add back the camera option to take pics with marauder directly

**Comment by runcom** [comment]
also, the wardrive functionality works paired with my other PR and gps setup :) you get the wardrive log file with gps info too :)

**Comment by eried** [comment]
Thanks! I will test it tonight and merge :)

**Comment by eried** [comment]
I will directly update to 1.0, but I have some space problems

**Pull request closed without merging**
