### PR TITLE
enable GPS and document pinout for esp32-cam

### LINKED ISSUE #41: adding a gps module
Hi, I'm trying to make a sense of how to add the gps module to the mayhem v2 board, is there any documentation about it? I can see the code mentioning the gps pins and such but wiring wise, I'm kind of lost. I can see that the mmc is set to use just 1 pin so I'm guessing the others should be free to wire up? or are they being used by the nrf/cc modules?

### PR DESCRIPTION
**Pull request by runcom**
closes #41

### CODE REVIEW

**Comment by eried** [comment]
😲 the sd card functionality works ok? can you take a photo from marauder companion?

**Comment by runcom** [comment]
> 😲 the sd card functionality works ok? can you take a photo from marauder companion?

yup, everything works as expected afaict, I can run `photo` from the cmdline and it works - logs shows everything Ready too - I'll be back this weekend for further testing tho if you have other things in mind to check

**Comment by runcom** [comment]
works like a charm, tested multiple time :)

**Comment by runcom** [comment]
~~the only thing that I'm debugging that "doesn't work" is the camera mayhem app - it just isn't working and I don't understand why, I can use the `photo` command just fine, using it from marauder too but when I use the camera app, nothing shows up - it's not realted to GPS though - I think it's something with the latest esp32 marauder firmware maybe? I've tested on serveral esp32cam now including yours but nothing~~ never mind this works great and it’s something else

**Comment by eried** [comment]
> never mind this works great and it’s something else

something else with the camera? 😅

**Comment by runcom** [comment]
> something else with the camera? 😅

it's not camera related, it's more about the `setup()` function and the way apps communicate over serial to pick the correct loop to run - on momentum, I have to patch the retry count and increase it when it sends something to the esp32cam to change function loop - I'm not sure where that behavior comes from

**Comment by eried** [comment]
I will add this as a reference to the wiki instead of PR

**Pull request closed without merging**
